FROM node:20-alpine AS builder

WORKDIR /workspace

RUN corepack enable yarn

COPY . .

RUN cd frontend && yarn install --frozen-lockfile && VITE_API_URL=https://impartial-magic-production-4d73.up.railway.app yarn build

FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /workspace/frontend/dist ./dist

EXPOSE 3000

CMD ["sh", "-c", "serve -s dist -l ${PORT:-3000}"]
