
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";



import { StackHandlerRoutes, LoginRedirect } from "app/auth";


import App from "./pages/App.tsx";
import Convert from "./pages/Convert.tsx";
import VeganWeapons from "./pages/VeganWeapons.tsx";

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect /> },
	{ path: "/auth/*", element: <StackHandlerRoutes /> },
	{ path: "/", element: <App /> },
	{ path: "/convert", element: <Convert /> },
	{ path: "/vegan-weapons", element: <VeganWeapons /> },
	{ path: "/veganweapons", element: <VeganWeapons /> },

];
